# Generated by Django 5.1.5 on 2025-01-19 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='diziler_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dizi_adi', models.TextField()),
                ('dizi_aciklama', models.TextField()),
                ('dizi_konusu', models.TextField()),
                ('dizi_imbd', models.TextField()),
                ('dizi_gorsel', models.TextField()),
                ('anasayfa', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='kategori_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
    ]
